name: Jira Exporter Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # Runs every hour

jobs:
  run-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Run Jira Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: jira
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.port.io"
          config: |
            jira_host: "https://keerthanas.atlassian.net"
            atlassian_user_email: ${{ secrets.atlassianUserEmail }}
            atlassian_user_token: ${{ secrets.atlassianUserToken }}
